### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by FloGo3308** [xMistt/fortnitepy-bot#101]
When I try to set an emote or skin by name (not cid_ or eid_) I get this error. I have ran this program for 1,5 days without any problems, but since the last time is started it up, it does this.
I get this error when i get an skin:
```
Task exception was never retrieved
future: <Task finished coro=<event_friend_message() done, defined at fortnite.py:268> exception=AttributeError("'str' object has no attribute 'get'")>
Traceback (most recent call last):
  File "fortnite.py", line 283, in event_friend_message
    backendType="AthenaCharacter"
  File "/home/pi/.local/lib/python3.7/site-packages/BenBotAsync/__init__.py", line 174, in get_cosmetic
    return BRCosmetic(data)
  File "/home/pi/.local/lib/python3.7/site-packages/BenBotAsync/cosmetics.py", line 45, in __init__
    self.id = data.get('id')
AttributeError: 'str' object has no attribute 'get'
```
or this one with an emote:
```
Task exception was never retrieved
future: <Task finished coro=<event_friend_message() done, defined at fortnite.py:268> exception=AttributeError("'str' object has no attribute 'get'")>
Traceback (most recent call last):
  File "fortnite.py", line 319, in event_friend_message
    backendType="AthenaDance"
  File "/home/pi/.local/lib/python3.7/site-packages/BenBotAsync/__init__.py", line 174, in get_cosmetic
    return BRCosmetic(data)
  File "/home/pi/.local/lib/python3.7/site-packages/BenBotAsync/cosmetics.py", line 45, in __init__
    self.id = data.get('id')
AttributeError: 'str' object has no attribute 'get'
```
Am I doing something wrong?

**Comment by xMistt** [comment]
Nope, let me look into it.

**Comment by xMistt** [comment]
Can you tell me exactly what you searched for when getting this error? Like what did you type after ``!skin``.

**Comment by xMistt** [comment]
Have you received this error again? Closing ticket soon if no response. 👍
