### ISSUE TITLE
It keeps writing me trackmode ... line 193

### ISSUE THREAD

**Issue by msc1234** [xMistt/fortnitepy-bot#106]

**Comment by xMistt** [comment]
The full traceback would help. :)

**Comment by ArchieMaddog** [comment]
Traceback (most recent call last):
  File "fortnite.py", line 193, in <module>
    data = json.load(f)
  File "C:\Users\Archie Maddog\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Archie Maddog\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Archie Maddog\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Archie Maddog\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 9 column 14 (char 271)

**Comment by xMistt** [comment]
https://github.com/xMistt/fortnitepy-bot/issues/102#issuecomment-619696947

**Comment by yourmum906** [comment]
Can I have a bot
