### ISSUE TITLE
List error

### ISSUE THREAD

**Issue by BuRn-sensei-GGT** [xMistt/fortnitepy-bot#114]
When I open the run file it returns the following error from: fortnitepy/http.py file:
AttributeError: 'list' object has no attribute 'cls'

I understand a little about python but not enough to fix this.

**Comment by xMistt** [comment]
Can you send me the full traceback? :)

**Comment by BuRn-sensei-GGT** [comment]
Here:

Traceback (most recent call last):
  File "fortnite.py", line 1155, in <module>
    client.run()
  File "C:\Users\jt\AppData\Local\Programs\Python\Python37\lib\site-packages\fortnitepy\client.py", line 640, in run
    return future.result()
  File "C:\Users\jt\AppData\Local\Programs\Python\Python37\lib\site-packages\fortnitepy\client.py", line 610, in runner
    await self.start()
  File "C:\Users\jt\AppData\Local\Programs\Python\Python37\lib\site-packages\fortnitepy\client.py", line 682, in start
    await self._login()
  File "C:\Users\jt\AppData\Local\Programs\Python\Python37\lib\site-packages\fortnitepy\client.py", line 778, in _login
    await self.initialize_party()
  File "C:\Users\jt\AppData\Local\Programs\Python\Python37\lib\site-packages\fortnitepy\client.py", line 971, in initialize_party
    await self._create_party()
  File "C:\Users\jt\AppData\Local\Programs\Python\Python37\lib\site-packages\fortnitepy\client.py", line 2391, in _create_party
    data = await self.http.party_create(cf)
  File "C:\Users\jt\AppData\Local\Programs\Python\Python37\lib\site-packages\fortnitepy\http.py", line 1257, in party_create
    conn_type = conf.cls.CONN_TYPE
AttributeError: 'list' object has no attribute 'cls'

**Comment by xMistt** [comment]
What version of fortnitepy do you have? If you don't know how to check, type this into command prompt:

```
py -3 -c "import fortnitepy;print(fortnitepy.__version__)"
```

**Comment by BuRn-sensei-GGT** [comment]
2.0.3

**Comment by xMistt** [comment]
Terbau has said he'll look into this, I'll keep you updated.

**Comment by BuRn-sensei-GGT** [comment]
Yes sir.

**Comment by xMistt** [comment]
Reinstall the bot and tell me if you still get this error.

**Comment by BuRn-sensei-GGT** [comment]
New error:

Traceback (most recent call last):
  File "fortnite.py", line 203, in <module>
    if data['debug']:
KeyError: 'debug'

**Comment by xMistt** [comment]
Send your config.json.

**Comment by BuRn-sensei-GGT** [comment]
{
    "email": "---@---.com",
    "password": "---",
    "cid": "CID_022_Athena_Commando_F",
    "bid": "BID_527_Loofah",
    "eid": "EID_Loofah",
    "banner": "otherbanner28",
    "banner_colour": "defaultcolor15",
    "level": 999,
    "bp_tier": 999999999,
    "status": "Test",
    "platform": "WIN",
    "debug": false,
    "friend_accept": true
}

**Comment by xMistt** [comment]
Is your fortnitepy-bot directory unzipped?

**Comment by BuRn-sensei-GGT** [comment]
Yes.

**Comment by xMistt** [comment]
I've honestly got no idea. The issue you originally posted was due to your fortnite.py file being outdated.

**Comment by BuRn-sensei-GGT** [comment]
Ok... I'll try to get it working. If I do, I'll tell you what I did.

**Comment by BuRn-sensei-GGT** [comment]
What version of fortnite.py is used?

**Comment by xMistt** [comment]
Latest.

**Comment by BuRn-sensei-GGT** [comment]
I'm not sure what changed but after updating the bot and reinstalling the packages it works.

Awesome bot by the way.
