### ISSUE TITLE
can't invite the bot

### ISSUE THREAD

**Issue by osama1433** [xMistt/fortnitepy-bot#119]
Task exception was never retrieved
future: <Task finished coro=<event_party_member_join() done, defined at C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnite.py:263> exception=AttributeError("'NoneType' object has no attribute 'edit_and_keep'",)>
Traceback (most recent call last):
  File "C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnite.py", line 265, in event_party_member_join
    await BenBotAsync.set_default_loadout(client, data, member)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\BenBotAsync\__init__.py", line 81, in set_default_loadout
    await party_update_meta.me.edit_and_keep(  # Sets default loadout.
AttributeError: 'NoneType' object has no attribute 'edit_and_keep

**Comment by xMistt** [comment]
Downgrade to fortnitepy 1.7.1.
