### ISSUE TITLE
Exchange code

### ISSUE THREAD

**Issue by kaaax0815** [xMistt/fortnitepy-bot#124]
If I put the exchange code in everything's fine.
If I restart the bot I have to do it again.
Is there anyway to bypass this?

**Comment by xMistt** [comment]
After first time setup it should set it device auths which would bypass this. Is your device_auths.json empty after first time start up or no?

**Comment by kaaax0815** [comment]
Yes
`Exception in callback BaseSelectorEventLoop._add_reader(0, <bound method...rt fd=0 idle>>)
2020-05-23T15:34:54.417276+00:00 app[worker.1]: handle: <Handle BaseSelectorEventLoop._add_reader(0, <bound method...rt fd=0 idle>>)>
2020-05-23T15:34:54.417277+00:00 app[worker.1]: Traceback (most recent call last):
2020-05-23T15:34:54.417277+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/selector_events.py", line 253, in _add_reader
2020-05-23T15:34:54.417278+00:00 app[worker.1]:     key = self._selector.get_key(fd)
2020-05-23T15:34:54.417282+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/selectors.py", line 191, in get_key
2020-05-23T15:34:54.417282+00:00 app[worker.1]:     raise KeyError("{!r} is not registered".format(fileobj)) from None
2020-05-23T15:34:54.417283+00:00 app[worker.1]: KeyError: '0 is not registered'
2020-05-23T15:34:54.417283+00:00 app[worker.1]: 
2020-05-23T15:34:54.417284+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2020-05-23T15:34:54.417284+00:00 app[worker.1]: 
2020-05-23T15:34:54.417285+00:00 app[worker.1]: Traceback (most recent call last):
2020-05-23T15:34:54.417285+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/events.py", line 145, in _run
2020-05-23T15:34:54.417285+00:00 app[worker.1]:     self._callback(*self._args)
2020-05-23T15:34:54.417286+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/asyncio/selector_events.py", line 256, in _add_reader
2020-05-23T15:34:54.417286+00:00 app[worker.1]:     (handle, None))
2020-05-23T15:34:54.417287+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/selectors.py", line 412, in register
2020-05-23T15:34:54.417287+00:00 app[worker.1]:     self._epoll.register(key.fd, epoll_events)
2020-05-23T15:34:54.417292+00:00 app[worker.1]: PermissionError: [Errno 1] Operation not permitted
2020-05-23T15:34:54.417589+00:00 app[worker.1]: Please enter the exchange code for berndxxxxxxp@outlook.com`

**Comment by xMistt** [comment]
Heroku doesn't save files when the dyno restarts. Either create device auths locally or get a VPS.
