### ISSUE TITLE
Traceback (most recent call last):   File "fortnite.py", line 46, in <module>     import BenBotAsync   File "C:\Users\OfferUp\AppData\Local\Programs\Python\Python36\lib\site-packages\BenBotAsync\__init__.py", line 49, in <module>     raise ValueError('Please update your fortnitepy to 2.0.0+.') ValueError: Please update your fortnitepy to 2.0.0+.

### ISSUE THREAD

**Issue by Joe678399** [xMistt/fortnitepy-bot#147]

**Comment by xMistt** [comment]
Update your fortnitepy to a version older than 2.0.0.
