### ISSUE TITLE
When launching the fortnite.py bot, this happends (I cant use the bot)

### ISSUE THREAD

**Issue by NathanTurnYT** [xMistt/fortnitepy-bot#155]
This is my log :

[PartyBot] [09:09:55] PartyBot made by xMistt. Massive credit to Terbau for creating the library.
[PartyBot] [09:09:55] Discord server: https://discord.gg/fnpy - For support, questions, etc.
main failed
Traceback (most recent call last):
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\node.py", line 843, in _on_main_done
    task.result()
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\node.py", line 1010, in _main
    yield from self._main_impl()
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\node.py", line 970, in _main_impl
    logger=self.logger)
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\node.py", line 385, in connect_xmlstream
    jid, metadata, negotiation_timeout, loop, logger,
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\node.py", line 278, in _try_options
    features=features,
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\security_layer.py", line 1200, in negotiate_sasl
    raise last_auth_error
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\security_layer.py", line 1184, in negotiate_sasl
    jid, features, xmlstream, transport)
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\security_layer.py", line 982, in execute
    intf, mechanism, token)
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\security_layer.py", line 847, in _execute
    yield from mechanism.authenticate(sm, token)
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aiosasl\__init__.py", line 605, in authenticate
    username, password = yield from self._credential_provider()
  File "C:\Users\NT\AppData\Local\Programs\Python\Python36\lib\site-packages\aioxmpp\security_layer.py", line 959, in credential_provider
    text="authentication aborted by user")
aiosasl.AuthenticationFailure: user intervention: authentication failed: authentication aborted by user

**Comment by fazfoxy1** [comment]
This is a issue on the library level so it is not going to be fixed by Oli and you have to wait for terbau to push a fix which might not be for a bit

**Comment by NathanTurnYT** [comment]
it was working, but now it doesnt work and i didnt install or modify anything.

**Comment by Brent43275** [comment]
I'm sure this issue, will be resolved in the near future.

**Comment by fazfoxy1** [comment]
![Screenshot_20200625_145438](https://user-images.githubusercontent.com/58317599/85739463-b8fdb200-b6f8-11ea-9d47-e7ecf43cf446.jpg)

**Comment by fazfoxy1** [comment]
That's the person who works on the library said about this

**Comment by Brent43275** [comment]
Yep.

**Comment by xMistt** [comment]
Fixed in fortnitepy v2.10.
