### ISSUE TITLE
inviting issue

### ISSUE THREAD

**Issue by osama1433** [xMistt/fortnitepy-bot#166]
when invite the bot with 3 or 4 players or more
Task exception was never retrieved
future: <Task finished name='Task-5594' coro=<event_party_member_join() done, defined at C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnitepy-bot-master\fortnite.py:287> exception=AttributeError("'NoneType' object has no attribute 'edit_and_keep'")>
Traceback (most recent call last):
  File "C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnitepy-bot-master\fortnite.py", line 289, in event_party_member_join
    await BenBotAsync.set_default_loadout(client, data, member)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python38\lib\site-packages\BenBotAsync\__init__.py", line 92, in set_default_loadout
    await party_update_meta.me.edit_and_keep(  # Sets default loadout.
AttributeError: 'NoneType' object has no attribute 'edit_and_keep'

**Comment by xMistt** [comment]
I'll look into it.

**Comment by xMistt** [comment]
Fixed in fortnitepy 3.0.0.

**Comment by osama1433** [comment]
Task exception was never retrieved
future: <Task finished coro=<event_party_invite() done, defined at C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnitepy-bot-master\fortnite.py:270> exception=TimeoutError('Party join timed out.',)>
Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\client.py", line 2811, in _join_party
    await future
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\asyncio\tasks.py", line 356, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnitepy-bot-master\fortnite.py", line 272, in event_party_invite
    await invite.accept()
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\party.py", line 3478, in accept
    await self.client.join_party(self.party.id)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\client.py", line 2881, in join_party
    party = await self._join_party(party_data)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\client.py", line 2813, in _join_party
    raise asyncio.TimeoutError('Party join timed out.')
concurrent.futures._base.TimeoutError: Party join timed out.

**Comment by wavy0** [comment]
Try reinstalling the bot
