### ISSUE TITLE
!new command is broken

### ISSUE THREAD

**Issue by osama1433** [xMistt/fortnitepy-bot#177]
Task exception was never retrieved
future: <Task finished coro=<Bot._wait_for_error_return() done, defined at C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py:813> exception=CommandInvokeError("Command raised an exception: AttributeError: 'BRCosmetic' object has no attribute 'split'",)>
Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\core.py", line 59, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnite.py", line 1779, in new
    for new_skin in [new_cid for new_cid in new_skins if new_cid.split('/')[-1].lower().startswith('cid_')]:
  File "C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnite.py", line 1779, in <listcomp>
    for new_skin in [new_cid for new_cid in new_skins if new_cid.split('/')[-1].lower().startswith('cid_')]:
AttributeError: 'BRCosmetic' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py", line 819, in _wait_for_error_return
    ret = await self.wait_for_futures(futures, check=check)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py", line 808, in wait_for_futures
    if check is None or check(future):
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py", line 817, in check
    return future.result() is False
  File "C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnite.py", line 312, in event_command_error
    raise error
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py", line 851, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\core.py", line 848, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\core.py", line 68, in wrapped
    raise errors.CommandInvokeError(exc) from exc
fortnitepy.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'BRCosmetic' object has no attribute 'split'

**Comment by xMistt** [comment]
Sorry about that, I'll need to fix it.

**Comment by osama1433** [comment]
hopefully this fixed very soon

**Comment by xMistt** [comment]
It's fixed now, sorry for the wait.
