### ISSUE TITLE
promote command not working 

### ISSUE THREAD

**Issue by osama1433** [xMistt/fortnitepy-bot#192]
when i use !promote command it says
Task exception was never retrieved
future: <Task finished coro=<Bot._wait_for_error_return() done, defined at C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py:817> exception=CommandInvokeError("Command raised an exception: AttributeError: 'list' object has no attribute 'get'",)>
Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\core.py", line 59, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnitepy-bot-master\partybot\party.py", line 191, in promote
    member = self.bot.party.members.get(user.id)
AttributeError: 'list' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py", line 823, in _wait_for_error_return
    ret = await self.wait_for_futures(futures, check=check)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py", line 812, in wait_for_futures
    if check is None or check(future):
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py", line 821, in check
    return future.result() is False
  File "C:\Users\Gamer\Desktop\fortnitepy-bot-master\fortnitepy-bot-master\partybot\bot.py", line 197, in event_command_error
    raise error
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\bot.py", line 855, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\core.py", line 848, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Gamer\AppData\Local\Programs\Python\Python36\lib\site-packages\fortnitepy\ext\commands\core.py", line 68, in wrapped
    raise errors.CommandInvokeError(exc) from exc
fortnitepy.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'list' object has no attribute 'get'

**Comment by wavy0** [comment]
It's an error with fortnitepy.

**Comment by xMistt** [comment]
> It's an error with fortnitepy.
Incorrect, it's an issue on my behalf.

I'll look into it, thanks for the report.

**Comment by xMistt** [comment]
Fixed in https://github.com/xMistt/fortnitepy-bot/commit/e37a877ee21c55e854ce9b6859a652a25f564b7d.

**Comment by wavy0** [comment]
my mistake lol
