### ISSUE TITLE
/k

### ISSUE THREAD

**Issue by mryoursalty** [xMistt/fortnitepy-bot#198]
when i use start.bat i get 
C:\Users\my name\Desktop\New folder (3)\fortnitepy-bot-master>py fortnite.py
Traceback (most recent call last):
  File "fortnite.py", line 31, in <module>
    import asyncio
  File "C:\Users\my name\AppData\Local\Programs\Python\Python38\lib\asyncio\__init_
_.py", line 8, in <module>
    from .base_events import *
  File "C:\Users\my name\AppData\Local\Programs\Python\Python38\lib\asyncio\base_ev
ents.py", line 18, in <module>
    import concurrent.futures
  File "C:\Users\my name\AppData\Local\Programs\Python\Python38\lib\concurrent\futu
res\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\Users\my name\AppData\Local\Programs\Python\Python38\lib\concurrent\futu
res\_base.py", line 7, in <module>
    import logging
  File "C:\Users\my name\AppData\Local\Programs\Python\Python38\lib\logging\__init_
_.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "C:\Users\my name\AppData\Local\Programs\Python\Python38\lib\re.py", line 12
5, in <module>
    import sre_compile
  File "C:\Users\my name\AppData\Local\Programs\Python\Python38\lib\sre_compile.py"
, line 14, in <module>
    import sre_parse
  File "C:\Users\my name\AppData\Local\Programs\Python\Python38\lib\sre_parse.py",
line 28, in <module>
    _REPEATCODES = frozenset({MIN_REPEAT, MAX_REPEAT})
NameError: name 'MIN_REPEAT' is not defined

C:\Users\my name\Desktop\New folder (3)\fortnitepy-bot-master>cmd /k
C:\Users\my name\Desktop\New folder (3)\fortnitepy-bot-master>

**Comment by NathanTurnYT** [comment]
im having the same problem, pls fix it

**Comment by xMistt** [comment]
Are you still experiencing this issue if you reinstall packages?

**Comment by xMistt** [comment]
Due to lack of response, I'm going to close this issue. If either of you (@mryoursalty & @NathanTurnYT) experience this issue again, feel free to create another issue but just remember to respond to me if I have any questions.
