### ISSUE TITLE
Bot doesn't launch

### ISSUE THREAD

**Issue by NathanTurnYT** [xMistt/fortnitepy-bot#199]
When i try to launch, the bot gives an error. Probably the same problem as the Issue #198.

Log:

C:\Users\TheUser\Downloads\fortnitepy-bot-master latest for now\fortnitepy-bot-master>py fortnite.py
Traceback (most recent call last):
  File "C:\Users\TheUser\Downloads\fortnitepy-bot-master latest for now\fortnitepy-bot-master\fortnite.py", line 121, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\TheUser\Downloads\fortnitepy-bot-master latest for now\fortnitepy-bot-master\fortnite.py", line 82, in main
    await device_auths.load_device_auths()
  File "C:\Users\TheUser\Downloads\fortnitepy-bot-master latest for now\fortnitepy-bot-master\partybot\deviceauths.py", line 60, in load_device_auths
    data = json.loads(raw)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\TheUser\Downloads\fortnitepy-bot-master latest for now\fortnitepy-bot-master>cmd /k
C:\Users\TheUser\Downloads\fortnitepy-bot-master latest for now\fortnitepy-bot-master>

I hope it is fixed soon.
NOTE : It is probably an error with the API because i tested it with old versions that were working before, and they wasn't working.

**Comment by xMistt** [comment]
This is an issue /w your config. Either delete your config or fix the formatting so that JSON can parse it.

**Comment by NathanTurnYT** [comment]
I know this post is very old, but the issue was that im using 3.9 and the required version at the time was 3.7
