### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by neurax-serv** [xMistt/fortnitepy-bot#31]
listener attached to signal raised
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\aioxmpp\callbacks.py", line 536, in fire
    keep = wrapper(args, kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\aioxmpp\callbacks.py", line 470, in _strong_wrapper
    return not f(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\aioxmpp\dispatcher.py", line 287, in _feed
    super()._feed(stanza)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\aioxmpp\dispatcher.py", line 135, in _feed
    cb(stanza)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\fortnitepy\xmpp.py", line 645, in <lambda>
    lambda m: dispatcher.process_event(self.client, m)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\fortnitepy\xmpp.py", line 67, in process_event
    type_ = body['type']
TypeError: list indices must be integers or slices, not str

**Comment by xMistt** [comment]
Issue with ``fortnitepy``, Terbau said he would look into it.

**Comment by neurax-serv** [comment]
Can i downgrade the package to fix it?

**Comment by xMistt** [comment]
No as the error is happening because the Fortnite backend changed and it hasn’t been updated in fortnitepy yet.

**Comment by xMistt** [comment]
Fixed in ``fortnitepy`` 1.5.0, reinstall packages.
