### ISSUE TITLE
ConnectionError: connection timeout

### ISSUE THREAD

**Issue by PulseMedia** [xMistt/fortnitepy-bot#44]
Getting the following error:

`broker task failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aioxmpp/stream.py", line 1939, in _run
    timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 363, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 456, in _wait
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aioxmpp/stream.py", line 892, in _done_handler
    task.result()
  File "/usr/local/lib/python3.7/dist-packages/aioxmpp/stream.py", line 1987, in _run
    raise self._xmlstream_exception
ConnectionError: connection timeout (dead time hard limit exceeded)
stream failed: connection timeout (dead time hard limit exceeded)
`

**Comment by xMistt** [comment]
What platform is set in config?

**Comment by PulseMedia** [comment]
"WIN"

**Comment by xMistt** [comment]
Is there a PSN or Xbox account with the same name as the bots Epic name?

**Comment by PulseMedia** [comment]
@xMistt nope

**Comment by dominikds1999** [comment]
I've the same issue

**Comment by xMistt** [comment]
How many friends do the accounts have?

**Comment by PulseMedia** [comment]
@xMistt Zero :D

**Comment by xMistt** [comment]
Maybe report it to Terbau. 🤷‍♂

**Comment by xMistt** [comment]
Do you still receive the error?

**Comment by xMistt** [comment]
Deleted due to inactivity.
