### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by PepeElCalvo** [xMistt/fortnitepy-bot#50]
Traceback (most recent call last):
  File "fortnite.py", line 104, in <module>
    device_auth_details = get_device_auth_details().get(data['email'], {})
  File "fortnite.py", line 51, in get_device_auth_details
    return json.load(fp)
  File "C:\Users\leoli\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\leoli\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\leoli\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\leoli\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xMistt** [comment]
**What the error is & it's cause.**
The error: ``json.decoder.JSONDecodeError`` is caused by Python not being able to parse the config due to it not being in the correct format.

How to fix the error:
In order to fix this error, make sure your config.json isn't missing any commas, brackets, etc. Here is an example config:

```
{
   "email": "email@email.com",
   "password": "password1",
   "cid": "CID_022_Athena_Commando_F",
   "bid": "BID_023_Pinkbear",
   "eid": "EID_HiLowWave",
   "banner": "otherbanner28",
   "banner_colour": "defaultcolor15",
   "level": 999,
   "bp_tier": 999999999,
   "status": "Created by xMistt, enjoy!",
   "platform": "WIN",
   "debug": false,
   "friendaccept": true
}
```
